#!/bin/bash

platform=`uname -o`

if [ "$platform" == "GNU/Linux" ]; then
	yum -y install pcre.x86_64 pcre-devel.x86_64
fi

cd luajit-2.0

make

make install

cd ..

cd lua-cjson-2.1.0/
make
make install
cd ..

already=0
while read line
do
	   if [ "$line" == "/usr/local/lib" ]; then
		   already=1
	   fi
done < /etc/ld.so.conf
if [ $already == 0 ]; then
	echo "/usr/local/lib" >> /etc/ld.so.conf
fi
ldconfig

./configure --with-http_upstream_check_module --add-module=ngx_dynamic_proxy_pass_module --with-luajit-inc=/usr/local/include/luajit-2.0 --with-luajit-lib=/usr/local/lib/ --with-http_lua_module --add-module=ngx_http_dyups_module --add-module=nginx_upstream_hash/

make

make install
